{% set version = "2.3.0" %}

package:
  name: django-import-export
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-import-export/django-import-export-{{ version }}.tar.gz
  sha256: 21464304cb64e57809f3d6f5ad45108d5b02c556ab115b493a547304d2dddc70

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - tablib
    - django >=2.0
    - diff-match-patch

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - import_export
    - import_export.formats
    - import_export.templatetags

about:
  home: https://github.com/bmihelac/django-import-export
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Django application and library for importing and exporting data with included admin integration

extra:
  recipe-maintainers:
    - ocefpaf
