{% set version = "0.7.0" %}

package:
  name: django-import-export
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-import-export/django-import-export-{{ version }}.tar.gz
  sha256: 6e748fcc647fe2a82a55136ebcbe806a45fd7fb5b1e32b33759181f1e67eeb1b

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - tablib
    - diff-match-patch

test:
  imports:
    - import_export
    - import_export.formats
    - import_export.templatetags

about:
  home: https://github.com/bmihelac/django-import-export
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Django application and library for importing and exporting data with included admin integration.'

extra:
  recipe-maintainers:
    - ocefpaf
