{% set version = "0.6.1" %}

package:
  name: django-import-export
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-import-export/django-import-export-{{ version }}.tar.gz
  sha256: ee604dde22c4c8a9cd93660c1b8d9bc41ad4f0ab6177e34f04c0f164ca41ca58

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - tablib
    - diff-match-patch

test:
  imports:
    - import_export
    - import_export.formats
    - import_export.templatetags

about:
  home: https://github.com/bmihelac/django-import-export
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Django application and library for importing and exporting data with included admin integration.'

extra:
  recipe-maintainers:
    - ocefpaf
