travis:
  secure:
    BINSTAR_TOKEN: tOH2hbP8OpFlp6TbOQDRqWdh8Zs/NZAfXmr0/yPs3AIGlVELWB4SMNlNeDzoE/3JMdVf4kxXAXLXO1GSY2ja5+R5HmrNNCTZp84QrO7bsYwL47B/lXBQpdjLwCUiG9ApFRUl+2T7CLYfVHtG6SG1g2xPB8nO1hBB7u+Y9lEtiecpF047hNeKRDcZ4zeCX/joNfduZPaUr6zbVP3bWH0mPtVwbnILCTDp4C6GJHnat4FvLJjGvXdYGc3AIt9zZpO/VthqnEfYHJg/5tlyFJDrnxhs/d02Cyweb7kiFr/joYHTOE2CH+VzmZ2quOLlCZ4c6cBux+479A8ON2Kg6uuToh2mVn0xx2bvJ9uLcA2N9P2MtM+UoMktMLcSg/YCRUklGSlSM5HvH+GBVfZB+o8t94RBnIP/1r7BGK6Uz7+hebVSmSY+t9yXy0TgGRj1fX2YwBh7otJemlTS2aBE2z14NRiwIbJ2nwIicqoO/qLTs4Cen+lVXpdHE1rvk+d3+4nFxEdWLbliV3KfWQaVcvSX22FjXawYi734pMvgYG3JZ9LQnXomZGDf4KioEbT53iplI8xyYXRe/yYmr7jzVqullCexwnGmuBW9/o1zNn02Vss85Fh44TmP3wQH2NAUy2/2HzrgN2qdlDpmyJ6dSqUY+f1Ulp2ro/3saC5YX/Jyybs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
