travis:
  secure:
    BINSTAR_TOKEN: BPgQm1iUsPNc33/AWh0qStc200ZOSDFlhGe/5qa57N7+enKwoEOlKF1dBfsVEG3RGSqeUXwu2OwEASNPziZAnbmmMylzjKL66yaxwYbYjmG5/BRtq8focyr/EgQM0KGGofwxARXrU+fJho5DJLLGqz6QOet8LoA8O3PxpT+R8EkFWKq/ZQc8vUjPcPoi2ahYBJbuY+WZmsSN0+xA/LAqI7Vybl9UbprzMVa6vSwmLNzBppJXQ09f0A8O4+tH+24JTjROdRRkgo0JFJwK5TZKMGazFH+94ai/H9n4WzyT5kWWOwQWrapAqrXy50CRL5NIt2mreBFpH4+7mVgh9/sTirlM7P1pIThD4uxWP7rhOQd3iXIfX2MxnnZGYRpWg3BjRwvFIGkyEpSr+ZiU+AJFZ8RUVE3bOi5OC2QCoVcroFiEBoL3ctxGPkewCNoeA/3FJjRRx25pI0IColq+L1mXZY9k3P597hWCIlWok6oEsVXR2o+teKoFKiqjon55v6gRaehluRJ8yyCKIBEt+lA031P0q6RVUUyDwyr3IgUMe8UWF+dK0Bc9FTNKpcPAn6pqB3igyMWnyvuaf0klL/3IDappJFG7kYv7uWCIQoUuSzOVrRsQs0TiNy/QjXOGW+KXTYcCQXqLMBT0lHgkw9yw4Yb95Gz2LCunqAKv6r9uXtc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
