travis:
  secure:
    BINSTAR_TOKEN: C9qX2mTtKF07zcNZJ+ax3S86Rtm/7e0WiZYGRAC0CHod1YIYhXhTIqDOMo9kRqQ+SAkXtuCAoVcydMNcshXh9z8hLFtFv+/1k7rz3RhaY5bwl+BB76Fd2xv3PRfZY/ac1QCc9ykjOdhjDMqZfKRpzlT6obvX1c33tvCdxaoCMAFasHayrCOhzoMciRF5H85QbXR+koJX3iOEJpuVhrfQn1NGM3tGWn2uGeS5XMSeroEVy5swNdVCTgYGanH07CXCdhYdaeJf+YObvLYMHoMOkhOySJ5IyTGtY4X2IY26rf7rUM9mQAOgXgmLJGziIzHU06aXF8ElQzWkqP0v7KMsyHKIlFNc9GLYKX3QCWWxirEh0S0tbL7kXVF4Q6UYiq8b/7abRBLJaA6w9gVBsGX486S7HoINfiN9k6UHWm79Izg6v8CSuCbV6+/AIm05s+h0aXoToVmwDBVxULGmYzn7lrViIshvQ/ptVJ2QVrjCZUKmwy/AjeAK86A8w0MkFhUzLIwFyi7pzUfMh/eX/9zXUBq3sDR9JMgKWnj/h9T3tjOwvO7gSPP8Wt9uMA2fsT0WpMjglQ5PyCKYfWP/5ScbUoqE1fAEnI+I/R/NXSvcgowC/iexCqK9geZjOM0b6odb8nZ6lEgPKLAQfntBgaeVmOCYsQqxY0aSZ/m+Yunk5Ek=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
